<!DOCTYPE html>
<html>
<head>
    <base href="/">
    <title>Обратная связь - Irina Zhunusova</title>
    <meta charset="UTF-8">
    <meta name="description" content="Envybox - Тестовое задание на позицию PHP + VueJs Разработчик">
    <meta name="author" content="Irina Zhunusova">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>
    <div id="app"></div>
</body>
</html>